{% set version = "1.1.4" %}

package:
  name: paegan
  version: {{ version }}

source:
  fn: paegan-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/paegan/paegan-{{ version }}.tar.gz
  sha256: a9d7308315274734738ff32e09611e2799c6136ad41f0b1f1865a7b8db693ba6

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - shapely
    - pytz
    - python-dateutil

test:
  imports:
    - paegan
    - paegan.logger
    - paegan.roms
    - paegan.cdm.grids
    - paegan.cdm
    - paegan.external
    - paegan.cdm.dsg.collections.base
    - paegan.utils
    - paegan.cdm.dsg.features.base
    - paegan.cdm.dsg.features
    - paegan.cdm.dsg.collections
    - paegan.cdm.dsg

about:
  home: https://github.com/axiom-data-science/paegan
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: 'Paegan - The Python CDM for Met/Ocean data.'

extra:
  recipe-maintainers:
    - ocefpaf
