travis:
  secure:
    BINSTAR_TOKEN: HEEnRqFPg1i0r2E2wA1EcQikCpq1O7bcECaHdJWa5zEQBJrQ2+Hy56wDGgTfI5XCObYeaARLiLYDTW0z7MhkMacN1S6YMnZv7JxhRxgI/s/SqrJpYgD5E48CITgLLoGaicTvktv3ul+TDt8gmUGHh16K2+r2bk9KRFdDDdafSSVKO0ePxFVol+FcBooAOVE0J5dZommoUfe1nOxiKSxVYdeKAiuLNW09/B/cno/CsYrvftppHQhtdw5y3VRAFi8mIjgglX7O/O9ZrC+90cAcxSxkEn9waufldrYwhzmgVxvLQJqaZfVYZRrEQyrC6RNAJUnUla3GSQlTYEV42iYulKbfbhyzN21wfVn/1Qbxdw5qI8JRkYP73TL78H36c8FoXND0HCdSv6sK13r/szG18IwtDTAa+owWAQUKdkiFPt9fUs+/3I/Vnp6a9hMpNXcMek+yLz1vJiYJsNFHOUUvZJoZlLHUTu0xCcQpi9do+Yhco38lJdn5c5lGGnpNjGBh+92L3Nigta45PoWSS/UsvnWI/l2VCievywGCpCg4JcYDGxCl4+ofJUyD+4oo3IiMz/nU6UofOcON4+VVrM2N+DAvF/ZxxLe3kIiD9leBaJL4vgrPMSsZONdHDUv8+EoMh+TVMO6c0lGqV5LQz6b1bL+LidYZanQKXTLdqNS4cNU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
