travis:
  secure:
    BINSTAR_TOKEN: dWyabSjlwxxAx+CwJEaNQXI3XmFWkO2rKTBGGUiz7lofOyhrwbWzvKN8p0TEkxkOot2fCCMwHQz88ShoTqkk9arXzqu/V6CSelVGAfgKDGIkBFlEbpIx4Tlv9/oP5QOs45p/G6bUKAb06gUo1KT8x6cEDCoYWnfyIZMRoBvKwEVTuMcTBR45BqwhvL9VHp1fElBk9dJeFb36VXHCSo/XLevWigIrznijJOI9xCMqAieZn50914/R5qDwqzNkf7YADUdXKdD47auhnQ36oHX1c2dDaFGNC3iHTZRgnvESTVZh+nCD0ywnGLxg02qBbEiBy+SrRWTdvHv8wC4y6Y2OpxfmdaE0kE/tqjO1Lu6ChETT+6NHYR5KyFNlPQ4bYYpJ4K6X2EOiQrTVT4+UzcTWkRoVttKXhXS242LUzDuWNLchBrHMrhP844RBddtKGbOlwfCeBQimn1mhNAE4vdcblye4afLQF33q+hMV29KJliO1WY2A06BQxliwC+RH1bLnlsaAY8oPYVVRmKtCjrBRr4ClOTzL+Zm3BSIUbWTYIH9JXvH/VKuVuKCTVRvCrH+qYuWIWyJE89CeNT+iGph2bjugAgxsLw9/B9zOd6A+yapoq5/pbB9cTVD6YgRUJIKk/a3pPoj4O8alB8AdXq/PoCuTBa/mOkPQ7SVpd854MHI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
